name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Continuous Integration (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
      # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
      - name: Build & Test
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cl.exe /Fe:build build.c
          build.exe -d build test
  macos:
    name: Continuous Integration (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build & Test
        run: |
          clang -o build build.c 
          ./build -d build test
  ubuntu:
    name: Continuous Integration (Ubuntu)
    strategy:
      matrix:
        cc:
          - clang
          - gcc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build & Test
        run: |
          ${{ matrix.cc }} -o build build.c 
          ./build -d build test
